baseURL = 'https://azrael-iii.github.io/neocom.github.io/'
languageCode = 'fr'
title = 'NEOCOM'
theme = 'terminal'

[[menu.main]]
  name = "A propos"
  url = "/a-propos"

[[menu.main]]
  name = "Musique"
  url = "/Musique"
  
[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/HQueenston64804"
  pre = "<i class='fab fa-twitter'></i>"
  
[[menu.footer]]
  name = "A propos"
  url = "/a-propos"

[markup.goldmark.renderer]
  unsafe= true

[params]
  enableEmoji= true

[languages]
  [languages.fr]
    [languages.fr.params]
      languageName = "Français"
      title = "Neocom"
      owner = "Azrael Queenston"
      copyright = "(1992 - 2025) - Azrael Queenston"
      missingContentMessage = "Page non trouvée..."
      missingBackButtonLabel = "Retour à l'accueil"

    [languages.en.params.logo]
      logoText = "NEOCOM"
      logoHomeLink = "https://azrael-iii.github.io/neocom.github.io/"
